### PR TITLE
Fix random.uniform and injectFaultFloor

### PR DESCRIPTION
**Pull request by ElaineYao**
1. `random.uniform` is used in TensorFlow v2. Since TensorFI is only compatible with TensorFlow v1, the equivalent code should be `random_uniform`  
2. Add `injectFaultFloor` function.

### CODE REVIEW

**Comment by PhuongLe** [comment]
I encountered the same issues when using TensorFI with an AV model, PilotNet, and also had the same fixes. It's good to see that there is PR for it.

**Comment by nniranjhana** [comment]
Hi @ElaineYao many thanks for your fix, could you remove the "Fixed issues with overflow" commit from this PR since we merged it already? Otherwise it looks good.

**Comment by ElaineYao** [comment]
OK, I make a create another PR without 'overflow issue'.

**Comment by ElaineYao** [comment]
OK, I create a another PR without 'overflow' issue.

**Comment by nniranjhana** [comment]
Thanks

**Pull request closed without merging**
