### PR TITLE
Modify install scripts and README

### PR DESCRIPTION
**Pull request by nniranjhana**
Source ~/.bashrc doesn't usually work from the script
as it is not interactive. Split the installation scripts
so users are requested to do it before the second script.

Updated README by moving common sections out of the
installation and better structuring the logical flow.

Remove Manual file as all info have been ported to Wiki
pages now.

Signed-off-by: Niranjhana Narayanan <nniranjhana@ece.ubc.ca>

### CODE REVIEW

**Comment by nniranjhana** [comment]
Please see this - https://askubuntu.com/questions/64387/cannot-successfully-source-bashrc-from-a-shell-script

The `source ~/.bashrc` in the script wasn't working even if I enabled the interactive script. The existing script failed to install any packages to the conda env since path wasn't set. I've modified it so users do it manually in the middle and use two scripts now. Have updated README too.

I have also removed the lines

```
###
# Set python path for TensorFI
###
echo "To set python path for TensorFI in anaconda, type :"
echo "ln -s FullPathToTensorFiProject/TensorFI/ ~/anaconda/envs/tensorfi/lib/python2.7/site-packages/"
```
If you can justify why we need this, I will add it back.

Please review the changes before merge, thanks.

**Comment by zitaoc** [comment]
Hi NJ, here are some of my comments for your change.

1. For the bash script, if you found any issues when running it (which i haven't encountered actually), i'm fine with incorporating the new changes. 
2. The lines you've deleted are for creating symbolic link in anaconda env, such that we can import tensorfi in the env. I think you should add them back.
3. For the README, perhaps you can create a separate bullet point for the ``Running TensorFI test files after installation''
4. The WiKi link looks very good and it's well elaborated! In addition to these, i'm thinking about if we may have a high-level diagram/walkthrough on how tensorfi works (e.g., like a flow-chart between the tensorfi modules). And also, a simple example on how to create a new fi_op might be useful. These might be useful for people to debug and modify the code etc (the current page is a bit text-heavy though i think).

**Comment by nniranjhana** [comment]
Hi @zitaoc 

Thanks a lot for the review!

1. Yes, the issue is for most Ubuntu users, there's a line in the ~/.bashrc file which by default doesn't execute `source ~/.bashrc` from inside scripts. So when I was installing it, all conda commands failed and I had to do it manually and so I've split this for future users.
2. Yes, I added it back - although I didn't seem to need it.
3. Good catch! Modified it now.
4. That's a good idea - we should have diagrams and flow charts, will be easier for users to follow. Yes, creating a new op too. I'll follow these up separately.

**Comment by karthikp-ubc** [comment]
Zitao: I've assigned this to you. Please merge the code after reviewing the PR. Thanks.

**Pull request merged**
